#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Models.Canonical.EquipmentDomain
{
    [IsRoot()]
    public class EquipmentLocation : CmmsTrackedEntity
    {
        public const string Version = "1.0";

        public string AssetNumber { get; set; }

        public string MtmId { get; set; }

        public string ShopName { get; set; }

        public string LocationName { get; set; }

        public string Type { get; set; }

        public string BayName { get; set; }

        public string BaySection { get; set; }

        public bool IsOverflow { get; set; }

        public int Ordinal { get; set; }

        public int BayOrdinal { get; set; }

        public int BaySectionOrdinal { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }
    }
}