#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;

namespace Tlm.Fed.Models.Canonical.EquipmentDomain
{
    /// <summary>
    ///     Canonical model that represents an instance of measurement,
    ///     taken against specific piece of equipment.
    /// </summary>
    public class MeasurePointReading : CmmsTrackedEntity
    {
        /// <summary>
        ///     The mnemonic code of the characteristic, e.g. ....
        /// </summary>
        public string CharacteristicCode { get; set; }

        /// <summary>
        ///     The description of the characteristic this measure point represents.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        ///     The name of the dimension the measure point represents.
        /// </summary>
        public string Dimension { get; set; }

        /// <summary>
        ///     The ID Key of the piece of equipment the Measure Point belongs to.
        /// </summary>
        public string EquipmentId { get; set; }

        /// <summary>
        ///     The ID key of the Location where the measurement was taken.
        /// </summary>
        public string Location { get; set; }

        /// <summary>
        ///     The unit of measurement for the Value field.
        /// </summary>
        public string UOM { get; set; }

        /// <summary>
        ///     The value of the measurement.
        /// </summary>
        public string Value { get; set; }
    }
}