#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

namespace Tlm.Fed.Contexts.Site.Core.DataStoreModel
{
    /// <summary>
    /// </summary>
    public class SalesOrg
    {
        /// <summary>
        ///     Gets or sets the legal entity.
        /// </summary>
        /// <value>
        ///     The legal entity.
        /// </value>
        public string LegalEntity { get; set; }

        /// <summary>
        ///     Gets or sets the distribution channel.
        /// </summary>
        /// <value>
        ///     The distribution channel.
        /// </value>
        public string DistributionChannel { get; set; }

        /// <summary>
        ///     Gets or sets the division.
        /// </summary>
        /// <value>
        ///     The division.
        /// </value>
        public string Division { get; set; }

        /// <summary>
        ///     Gets or sets the name of the legal entity.
        /// </summary>
        /// <value>
        ///     The name of the legal entity.
        /// </value>
        public string LegalEntityName { get; set; }
    }
}