#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using MoreLinq;
using Tlm.Fed.Adapters.Maximo.Common.Configuration;

namespace Tlm.Fed.Adapters.Maximo.Site.Concrete
{
    public class MaximoSiteRequestBuilder
    {
        private HttpRequestMessage _httpRequestMessage;
        private List<string> queryParameters;
        public MaximoSiteRequestBuilder(MaximoEndpointConfig maximoConfig)
        {
            _httpRequestMessage = new HttpRequestMessage()
            {
                RequestUri = new Uri(maximoConfig.Url + "/maximo/api/os/SLB_R_LOCATION_API01"),
                Method = HttpMethod.Get,
            };

            _httpRequestMessage.Headers.Add("apikey", maximoConfig.RestApiKey);

            queryParameters = new List<string>()
            {                
                "lean=1",
                "oslc.select=*",
                "_dropnull=0",
                "collectioncount=1"
            };
            
        }

        public HttpRequestMessage Build()
        {
            _httpRequestMessage.RequestUri = new Uri(_httpRequestMessage.RequestUri.ToString() + "?" + string.Join('&', queryParameters));
            return _httpRequestMessage;
        }
        public MaximoSiteRequestBuilder WithSubBusinessLineBuilder(string subBusinessLine)
        {
            if (string.IsNullOrEmpty(subBusinessLine))
                return this;

            queryParameters.Add($"oslc.where=slb_sub_bl=\"{subBusinessLine}\"");
            return this;
        }
        public MaximoSiteRequestBuilder WithMaxItems(int maxItems)
        {
            queryParameters.Add($"oslc.pageSize={maxItems}");
            return this;
        }

        public MaximoSiteRequestBuilder WithStartIndex(int startIndex)
        {
            queryParameters.Add($"pageno={startIndex}");
            return this;
        }


    }
}