#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Fed.Models.Canonical.MasterData;
using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Contexts.Site.Core.RepresentationModel
{
    [KeyReference(typeof(BasinView))]
    [IsRoot]
    public class BasinViewRepresentation : Entity
    {
        public string Code { get; set; }

        public string BVGroup { get; set; }

        public string LongName { get; set; }

        public string Definition { get; set; }

        public string ParentCode { get; set; }

        public string Type { get; set; }

        public const string Version = "1.0";
    }
}