#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Newtonsoft.Json;

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;
using Tlm.Fed.Models.Canonical.MasterData;

namespace Tlm.Fed.Contexts.Site.Core.RepresentationModel
{
    [KeyReference(typeof(BusinessView))]
    [IsRoot]
    public class BusinessViewRepresentation : Entity
    {
        /// <summary>
        ///     BusinessViews are geographical
        /// </summary>
        [JsonProperty]
        public string BVGroup { get; set; }

        /// <summary>
        ///     MasterData Code representing the Unique Identity of the SLOrg unit
        /// </summary>
        [JsonProperty]
        public string Code { get; set; }

        [JsonProperty]
        public string Definition { get; set; }

        [JsonProperty]
        public string LongName { get; set; }

        [JsonProperty]
        public string Owner { get; set; }

        [JsonProperty]
        public string ParentCode { get; set; }

        [JsonProperty]
        public string ReportName { get; set; }

        [JsonProperty]
        public string Type { get; set; }

        public const string Version = "1.0";
    }
}