#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;
using Tlm.Fed.Models.Canonical.MasterData;

namespace Tlm.Fed.Contexts.Site.Core.RepresentationModel
{
    [KeyReference(typeof(SiteTypeMap))]
    [IsRoot]
    public class SiteTypeMapRepresentation : Entity
    {
        /// <summary>
        ///     Describes the source, for example "MAXIMO".
        /// </summary>
        public string Source { get; set; }

        /// <summary>
        ///     Describes the source key for the Site Type. Example "STORE"
        /// </summary>
        public string SourceKey { get; set; }

        /// <summary>
        ///     Describes the target for the Site Type. For example "MATEO".
        /// </summary>
        public string Target { get; set; }

        /// <summary>
        ///     Describes the target key for SiteType. Example "OPERATION"
        /// </summary>
        public string TargetKey { get; set; }

        public const string Version = "1.0";
    }
}