#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using MoreLinq;
using Tlm.Fed.Adapters.SAP.Common.Configuration;

namespace Tlm.Fed.Adapters.SAP.Site.Concrete
{
    public class SAPSiteRequestBuilder
    {
        private HttpRequestMessage _httpRequestMessage;

        public SAPSiteRequestBuilder(SAPEndpointConfig sapConfig)
        {
            _httpRequestMessage = new HttpRequestMessage()
            {
                RequestUri = new Uri(sapConfig.Url + "/eamplantdetails/plantDetailsSet?$expand=plantToWrkcntr($expand=wrkcntrToPerson)&$count=true"),
                Method = HttpMethod.Get,
            };

            _httpRequestMessage.Headers.Add("x-apikey", sapConfig.ApiKey);
            _httpRequestMessage.Headers.Add("x-sap-audience", sapConfig.SapAudience);
        }

        public HttpRequestMessage Build()
        {
            _httpRequestMessage.RequestUri = new Uri(_httpRequestMessage.RequestUri.ToString());
            return _httpRequestMessage;
        }
    }
}