FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
COPY /devops/certs/CA1.crt /devops/certs/CA2.crt /devops/certs/Root.crt /usr/local/share/ca-certificates/
RUN cd /usr/local/share/ca-certificates && update-ca-certificates

WORKDIR /app
EXPOSE 80

# Copy files from the artifact staging folder on agent
COPY Contexts.Site.API/out .

ENTRYPOINT ["dotnet", "Tlm.Fed.Contexts.Site.API.dll"]