#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Tlm.Fed.Contexts.Common.Configuration;
using Tlm.Fed.Contexts.Site.Core.DataStoreModel;
using Tlm.Fed.Framework.ApiSupport;
using Tlm.Fed.Framework.Internal.Configurers;
using Tlm.Sdk.AspNetCore.Configurers;

[assembly: ApiController]

namespace Tlm.Fed.Contexts.Site.API
{
    public class StartupForSiteApi : StartupForApi
    {
        public StartupForSiteApi(IWebHostEnvironment env) : base(env)
        {
            AddConfigurer(new StronglyTypedConfigurationConfigurer<FrameworkApiSupportConfig>());
            AddConfigurer(new StronglyTypedConfigurationConfigurer<MasterDistrictConfig>());
            AddConfigurer(new ApiConfigurer());
            AddConfigurer(new ApiSupportConfigurer());
            AddConfigurer(new ApiAuthConfigurer());
        }
    }
}