#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Models.Canonical.MasterData
{
    [Key("{0}", @"^.+$", nameof(Code))]
    [IsRoot()]
    public class BusinessTeam : Entity
    {
        public const string Version = "1.0";

        public string SortOrder { get; set; }

        public string Code { get; set; }

        public string Type { get; set; }

        public string LongName { get; set; }

        public string Definition { get; set; }

        public string Owner { get; set; }

        public string ParentCode { get; set; }

        public string ReportName { get; set; }

        public string Level1ParentCode { get; set; }

        public string Level2ParentCode { get; set; }

        public string Level3ParentCode { get; set; }

        public string Level4ParentCode { get; set; }

        public string Level5ParentCode { get; set; }

        public string Level6ParentCode { get; set; }
    }
}