#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Models.Canonical.MasterData
{
    [Key("{0:D}:{1}", @"^\d+:.+$", nameof(HierarchyID), nameof(ChildKey))]
    [IsRoot]
    public class EquipmentSystemMapping : Entity
    {
        public string HierarchyID { get; set; }

        public string Level { get; set; }

        public string LevelID { get; set; }

        public string Code { get; set; }

        public string ChildKey { get; set; }

        public string Name { get; set; }

        public string ParentKey { get; set; }

        public string Type { get; set; }

        public string ToolGroup { get; set; }

        public string ToolType { get; set; }

        public string ToolName { get; set; }

        public string ToolSize { get; set; }
    }
}