#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Models.Canonical.MasterData
{
    /// <summary>
    ///     Material Master
    /// </summary>
    [IsRoot()]
    public class Material : Entity
    {
        public const string Version = "1.0";

        /// <summary>
        ///     Base Unit of Measure of the Material
        /// </summary>
        public string BaseUOM { get; set; }

        /// <summary>
        ///     European Conformity Mark
        /// </summary>
        public string CeMark { get; set; }

        /// <summary>
        ///     Description of the Material, typically following a "Noun, Modifier" pattern
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        ///     Equipment Model Code
        /// </summary>
        public string EquipmentModelCode { get; set; }

        /// <summary>
        ///     Equipment Model Key : XREF to the associated Equipment Model
        /// </summary>
        public string EquipmentModelKey { get; set; }

        /// <summary>
        ///     Material number identifying the material AKA Part Number
        /// </summary>
        public string MaterialNumber { get; set; }

        /// <summary>
        ///     4-digit Manufacturing Product Line Code
        ///     EMS Product Line Code + a 4th digit indicating the financial treatment (FTE, component, Inventory, 3rd PArty)
        /// </summary>
        public string MFGProductLine { get; set; }

        /// <summary>
        ///     GEMS Part Type
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        ///     Material Specification Class of the Material.
        ///     Used to determine applicable attributes needed to describe the material
        /// </summary>
        public string MscCode { get; set; }

        /// <summary>
        ///     Lead Free indicator
        /// </summary>
        public string LeadFreeIndicator { get; set; }

        /// <summary>
        ///     EMS Product Line Code Ties this material into the EPIC and EMS Org Hierarchies
        /// </summary>
        public string ProductLineCode { get; set; }

        /// <summary>
        ///     Product Line Key : XREF to the associated Product Line int the EPIC Hierarchy
        /// </summary>
        public string ProductLineKey { get; set; }

        /// <summary>
        ///     Name of the Project in GEMS uses to govern the material.
        /// </summary>
        public string Project { get; set; }

        /// <summary>
        ///     Revision of the Material in GEMS. Revisions track the lifecycle of the material through all of its
        ///     Form/Fit/Function
        ///     modifications
        /// </summary>
        public string Revision { get; set; }

        /// <summary>
        ///     Restriction of Hazardous Substances Directive: Classification of the material indicating hazardous materials found
        ///     in electrical and electronic products
        /// </summary>
        public string RoHS { get; set; }

        /// <summary>
        ///     The Waste Electrical and Electronic Equipment Directive:
        ///     Used in conjunction with RoHS for Waste recovery and recycling
        /// </summary>
        public string WEEE { get; set; }
    }
}