#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Tlm.Fed.Models.Canonical.MasterData
{
    [JsonObject(ItemReferenceLoopHandling = ReferenceLoopHandling.Ignore)]
    public class ReferenceObject
    {
        [JsonProperty]
        //[JsonConverter(typeof(StringEnumConverter))]
        public string Level { get; set; }

        [JsonProperty]
        public string Type { get; set; }

        [JsonProperty]
        public string Value { get; set; }

        [JsonProperty]
        public string WkId { get; set; }

        [JsonProperty]
        public Dictionary<string, object> Attribute { get; set; }
    }
}