#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

#pragma warning disable 1591

namespace Tlm.Fed.Models.Canonical.MasterData
{
    [IsRoot()]
    public class SLOrgClassification : Entity
    {
        public const string Version = "1.0";

        /// <summary>
        ///     Group of the Classification
        /// </summary>
        public string Group { get; set; }

        /// <summary>
        ///     GeoMarket of the Classification
        /// </summary>
        public string ProductLine { get; set; }

        /// <summary>
        ///     Area of the Classification
        /// </summary>
        public string Area { get; set; }

        /// <summary>
        ///     GeoMarket of the Classification
        /// </summary>
        public string GeoMarket { get; set; }
    }
}