#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

namespace Tlm.Fed.Adapters.Qtrac.Common.Views
{
    /// <summary>
    ///     The PivotTCOData class
    ///     Represents the Database model for the vwpivottcodata view
    /// </summary>
    public class PivotTCOData
    {
        public string Azimuth { get; set; }

        public string BHP { get; set; }

        public string BHStaticTemperature { get; set; }

        public string BHT { get; set; }

        public string BitType { get; set; }

        public string Comments { get; set; }

        public string County { get; set; }

        public string DockName { get; set; }

        public string DockPhone { get; set; }

        public string DogLeg { get; set; }

        public string EndDepthMD { get; set; }

        public string EndDepthTVD { get; set; }

        public int? HeisenbergVersion { get; set; }

        public string HighCorrosive { get; set; }

        public string HighPressure { get; set; }

        public string HighShock { get; set; }

        public string HighTemperature { get; set; }

        public int? HSPMVersion { get; set; }

        public string Inclination { get; set; }

        public string InspectionCompany { get; set; }

        public string InspectionLevel { get; set; }

        public string InspectionPaperWork { get; set; }

        public int? LoadoutId { get; set; }

        public string MagSpacing { get; set; }

        public string MaxDLS { get; set; }

        public int? MaxwellVersion { get; set; }

        public string MonitoringCompany { get; set; }

        public string MudDensity { get; set; }

        public string MudPV { get; set; }

        public string MudPVTemp { get; set; }

        public string MudType { get; set; }

        public string MudViscosity { get; set; }

        public string PlannedFlowRate { get; set; }

        public string PlannedFlowRateMin { get; set; }

        public int? RX56 { get; set; }

        public string SeaDep { get; set; }

        public string ShippingInstructions { get; set; }

        public string StandPress { get; set; }

        public string StartDepthMD { get; set; }

        public string Status { get; set; }

        public string SurfTemp { get; set; }

        public string TruckingCompany { get; set; }
    }
}