#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Tlm.Fed.Adapters.Qtrac.Common.Configuration;

namespace Tlm.Fed.Adapters.Qtrac.Common
{
    public class DbContextConfigurer<T> where T : DbContext
    {
        public static void Configure
        (
            DbContextOptionsBuilder<T> builder,
            QtracConnectionConfiguration config
        )
        {
            builder
                .UseQtracSqlServer(config)
#pragma warning disable 618
                .ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning))
#pragma warning restore 618
                .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
        }
    }
}