#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Canonical model of the comment.
    /// </summary>
    public class Comment
    {
        /// <summary>
        ///     Default constructor.
        /// </summary>
        public Comment()
        {}

        public Comment(DateTime commentDate, string commentText, string commentedBy, string sourceRecordId)
        {
            CommentDate = commentDate;
            CommentText = commentText;
            CommentedBy = commentedBy;
            SourceRecordId = sourceRecordId;
        }

        /// <summary>
        ///     Type of the model.
        /// </summary>
        /// <summary>
        ///     Date time of the comment added
        /// </summary>
        public DateTime CommentDate { get; set; }

        /// <summary>
        ///     LDapAlias of the person who added the comment
        /// </summary>
        public string CommentedBy { get; set; }

        /// <summary>
        ///     Comment description
        /// </summary>
        public string CommentText { get; set; }

        /// <summary>
        ///     Comment Modified Date
        /// </summary>
        public string ModifiedBy { get; set; }

        /// <summary>
        ///     Comment ModifiedDate
        /// </summary>
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        ///     stores the Movementnumber
        /// </summary>
        public string SourceRecordId { get; set; }
    }
}