#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Equipment Type
    /// </summary>
    public class EquipmentType
    {
        public EquipmentType()
        {
            Equipment = new HashSet<Equipment>();
        }

        public bool? AllowBlockWo { get; set; }

        public bool? AsMaintainedFlag { get; set; }

        public bool? BlockEqpCreation { get; set; }

        public bool? BlockEqpCreationPc { get; set; }

        public bool? BlockEqpJunkingNonPc { get; set; }

        public bool? BlockFfwocreation { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime? CreationDate { get; set; }

        public string Description { get; set; }

        public string Designresponsibility { get; set; }

        public string Designstatus { get; set; }

        public bool? Dtr { get; set; }

        public decimal? Edtfactor { get; set; }

        public ICollection<Equipment> Equipment { get; set; }

        public int? EquipmentClassificationId { get; set; }

        public int EquipmentTypeId { get; set; }

        public int EquipmentTypeSiteId { get; set; }

        public bool? FatigueTool { get; set; }

        public bool? FieldTest { get; set; }

        public string FileCode { get; set; }

        public string FileCodeStatus { get; set; }

        public int? FmsKeyCodeId { get; set; }

        public string GeMsdescription { get; set; }

        public string GemsproductLine { get; set; }

        public decimal? Height { get; set; }

        public bool? Imte { get; set; }

        public bool? IsVisible { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public decimal? Length { get; set; }

        public bool LocalTool { get; set; }

        public bool? Lrde { get; set; }

        public bool? MaterialCertification { get; set; }

        public bool? MechanicalLifting { get; set; }

        public string MinRevLevel { get; set; }

        public bool? NonAsset { get; set; }

        public int? PaperlessAssetTypeId { get; set; }

        public string PartNumber { get; set; }

        public string PartNumberRevionLevel { get; set; }

        public string PartType { get; set; }

        public bool? Pressure { get; set; }

        public decimal? Price { get; set; }

        public string ProductCenter { get; set; }

        public int? ProductCenterId { get; set; }

        public bool? PushtoSwat { get; set; }

        public int? RefIntervalId { get; set; }

        public int? RefMaintGrpId { get; set; }

        public int? RefManufacturerId { get; set; }

        public bool Rmistool { get; set; }

        public bool? Serialized { get; set; }

        public DateTime? Statusdate { get; set; }

        public bool? ThirdPartyMaintenance { get; set; }

        public int? ToolHierarchyId { get; set; }

        public string Uom { get; set; }

        public decimal? Weight { get; set; }

        public decimal? Width { get; set; }
    }
}