#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Equipment
    /// </summary>
    public class Equipment
    {
        public int? AccountSiteId { get; set; }

        public string AssignedClient { get; set; }

        public string AssignedTo { get; set; }

        public bool? BlockWo { get; set; }

        public DateTime BuildDate { get; set; }

        public string BusinessUnitCode { get; set; }

        public string ClientBasket { get; set; }

        public decimal? CostUsd { get; set; }

        public string CountryofOrigin { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public int CurrLocationId { get; set; }

        public string CurrLocationType { get; set; }

        public string CustomReceiptNo { get; set; }

        public string CustomsEntry { get; set; }

        public string CustomsExportEntryNo { get; set; }

        public string CustomsExportReceiptNo { get; set; }

        public string CustomsExportStatus { get; set; }

        public string CustomsStatus { get; set; }

        public string DataHubSerialNo { get; set; }

        public string Deminimis { get; set; }

        public string Deposit { get; set; }

        public bool? Dfp { get; set; }

        public string DisposalApprovedBy { get; set; }

        public DateTime? DisposalApprovedDate { get; set; }

        public string DisposalInvoiceNumber { get; set; }

        public string Duty { get; set; }

        public int EquipmentId { get; set; }

        public Site EquipmentSite { get; set; }

        [ForeignKey(nameof(EquipmentSite))]
        public int EquipmentSiteId { get; set; }

        public EquipmentType EquipmentType { get; set; }

        public int EquipmentTypeId { get; set; }

        public string FileCode { get; set; }

        public int? FinancialOwner { get; set; }

        public decimal? Height { get; set; }

        public int HoldingSiteId { get; set; }

        public decimal? HrsEdt { get; set; }

        public decimal? HrsPump { get; set; }

        public decimal? HrsSinceLastSl { get; set; }

        public string Htccode { get; set; }

        public string ImportClient { get; set; }

        public DateTime? ImportDate { get; set; }

        public string ImportType { get; set; }

        public string IsDataHubDocFetched { get; set; }

        public string LastDateChange { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public DateTime? LastServiceDate { get; set; }

        public string LawsonId { get; set; }

        public string LegalEntity { get; set; }

        public decimal? Length { get; set; }

        public bool? Loaned { get; set; }

        public string LockedBy { get; set; }

        public DateTime? LockedDateTime { get; set; }

        public string LockedSession { get; set; }

        public string MasterFileCode { get; set; }

        public string MasterSerialNo { get; set; }

        public int? MatstestId { get; set; }

        public int? OldRefEqpStateId { get; set; }

        public int? OldRefEqpStatusId { get; set; }

        public string Oracleidfield { get; set; }

        public int OwnershipId { get; set; }

        public string PartNumber { get; set; }

        public string Ponumber { get; set; }

        public string ProductCenter { get; set; }

        public int? ProductCenterId { get; set; }

        public int? ProjectCodeMapId { get; set; }

        public string PurchaseInvoiceNo { get; set; }

        public string RadiusToolName { get; set; }

        public int RefEqpStateId { get; set; }

        public int RefEqpStatusId { get; set; }

        public int? RefMaintGrpId { get; set; }

        public int? RefManufacturerId { get; set; }

        public bool? Rental { get; set; }

        public string RevisionLevel { get; set; }

        public int? RmsId { get; set; }

        public int? RmsSiteid { get; set; }

        public string SalesInvoiceNo { get; set; }

        public string SapId { get; set; }

        public string SerialNo { get; set; }

        public decimal ShockMaxDur { get; set; }

        public decimal ShockMaxLevel { get; set; }

        public decimal ShockTotal { get; set; }

        public bool? ShopUseOnly { get; set; }

        public string Stampedfc { get; set; }

        public string Stampedsn { get; set; }

        public DateTime? TempIedate1 { get; set; }

        public DateTime? TempIedate2 { get; set; }

        public DateTime? TempIedate3 { get; set; }

        public decimal TempMax { get; set; }

        public int? ToolHierarchyId { get; set; }

        public string ValueShipmentCost { get; set; }

        public decimal? Width { get; set; }

        //public ICollection<WorkPack> WorkPack { get; set; }
    }
}