#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Facilitites Class
    /// </summary>
    public class Facilities
    {
        public string AreaName { get; set; }

        public string Basin { get; set; }

        public string BuiltAreaSqMeter { get; set; }

        public string ContactName { get; set; }

        public string Country { get; set; }

        public string CountrySubDivision { get; set; }

        public string FacilityAddressLine1 { get; set; }

        public string FacilityAddressLine2 { get; set; }

        public string FacilityAddressLine3 { get; set; }

        public string FacilityAddressName { get; set; }

        [Key]
        public int FacilityID { get; set; }

        public string FacilityName { get; set; }

        public string FacilityOwnership { get; set; }

        public string FacilityPhone { get; set; }

        public string FacilityPostalCode { get; set; }

        public string FacilityStatus { get; set; }

        public string FacilityType { get; set; }

        public string GeoMarketName { get; set; }

        public string INSCOPE { get; set; }

        public string LandAreaSqMeter { get; set; }

        public string Latitude { get; set; }

        public string Longitude { get; set; }

        public string MailingAddressLine1 { get; set; }

        public string MailingAddressLine2 { get; set; }

        public string MailingAddressLine3 { get; set; }

        public string MailingAddressName { get; set; }

        public string MailingCountry { get; set; }

        public string MailingCountrySubDivision { get; set; }

        public string MailingPopulatedPlaceName { get; set; }

        public string MailingPostalCode { get; set; }

        public string OriginBusiness { get; set; }

        public string PopulatedPlaceName { get; set; }

        public string Population { get; set; }

        public string RemainingAreaSqMeter { get; set; }

        public string ValidatedBy { get; set; }

        public DateTime ValidatedDate { get; set; }
    }
}