#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Model for tblIDistrictPlannedResource table
    /// </summary>
    public class JobResource
    {
        public bool? Active { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public DateTime? EndTime { get; set; }

        public int? HolesizejobmapId { get; set; }

        public int Id { get; set; }

        public int? JobCode { get; set; }

        public int? JobId { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime? LastModifiedDate { get; set; }

        public int? PlannedResourceId { get; set; }

        public int? ProductGroupId { get; set; }

        public int? ProductLineId { get; set; }

        public int? Quantity { get; set; }

        public DateTime? ShippingOutJobDate { get; set; }

        public DateTime? ShippingToJobDate { get; set; }

        public DateTime? StartTime { get; set; }

        public string ToolComingFromLocationDescription { get; set; }

        public int? ToolComingFromLocationId { get; set; }

        public int? ToolMasterId { get; set; }
    }
}