#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The LoadoutToolOptions Class
    ///     Represents the Database model for the LoadoutToolOptions table
    /// </summary>
    public class LoadoutToolOptions
    {
        public bool? DisplayOnImage { get; set; }

        public int? EtraceId { get; set; }

        public int Id { get; set; }

        public int? LoadoutImageMappingId { get; set; }

        public int LoadoutToolId { get; set; }

        public string MessageDisplay { get; set; }

        public string OptionValue { get; set; }

        public int? PositionOnImage { get; set; }

        public bool? PositionOnLeft { get; set; }

        public int? RMasterAttributeId { get; set; }

        public int? RMasterValueId { get; set; }

        public int ToolOptionId { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }
    }
}