#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The LoadoutTool Class
    ///     Represents the Database model for the LOADOUT_TOOL table
    /// </summary>
    public class LoadoutTool
    {
        public int? AttachmentId { get; set; }

        public int? AvailableQuantity { get; set; }

        public string DefaultRedirectSite { get; set; }

        public int? DefaultRedirectType { get; set; }

        public DateTime? EndDate { get; set; }

        public int? EtraceId { get; set; }

        public int Id { get; set; }

        public int? ImageId { get; set; }

        public bool? IsSubstituteTool { get; set; }

        public int? LeftImageAttachmentId { get; set; }

        public Loadout Loadout { get; set; }

        public int LoadoutId { get; set; }

        public int? Quantity { get; set; }

        public int? RequestedQuantity { get; set; }

        public string SignalComment { get; set; }

        public string Signalstrength { get; set; }

        public DateTime? StartDate { get; set; }

        public bool Template { get; set; }

        public RToolMaster ToolMaster { get; set; }

        [ForeignKey(nameof(ToolMaster))]
        public int ToolMasterId { get; set; }

        public List<TCOToolSet> ToolSets { get; set; }

        public int? TubularTool { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }
    }
}