#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The Loadout Class
    ///     Represents the Database model for the Loadout table
    /// </summary>
    public class LoadoutEdp
    {
        public bool? Active { get; set; }

        public DateTime? ActualShipDate { get; set; }

        public double? Azimuth { get; set; }

        public double? BhpDrop { get; set; }

        public double? BhStaticTemperatureDrop { get; set; }

        public double? BhtDrop { get; set; }

        public string BitTypeDrop { get; set; }

        public int? BoreHoleId { get; set; }

        public string Comments { get; set; }

        public string County { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string CreatedUser { get; set; }

        public string Dmlocation { get; set; }

        public string DockName { get; set; }

        public string DockPhone { get; set; }

        public bool? DoglegDrop { get; set; }

        public DateTime? EndDate { get; set; }

        public double? EndDepthMdDrop { get; set; }

        public double? EndDepthTvdDrop { get; set; }

        public int? EtraceId { get; set; }

        public bool? HighCorrosiveDrop { get; set; }

        public bool? HighPressureDrop { get; set; }

        public bool? HighShockDrop { get; set; }

        public bool? HighTemperatureDrop { get; set; }

        public int? HoleSizeId { get; set; }

        public int? HspmDrop { get; set; }

        public int Id { get; set; }

        public double? InclinationDrop { get; set; }

        public string InspectionCompanyDrop { get; set; }

        public string InspectionLevelDrop { get; set; }

        public string InspectionPaperworkDrop { get; set; }

        public bool? Is1Ctco { get; set; }

        public bool? IsHsh { get; set; }

        public virtual JobEdp Job { get; set; }

        [ForeignKey(nameof(Job))]
        public int JobId { get; set; }

        public string JobProbability { get; set; }

        public string LoadoutName { get; set; }

        public ICollection<LoadoutToolEdp> LoadoutTools { get; set; }

        public string LockedBy { get; set; }

        public string LockedBySite { get; set; }

        public DateTime? LockedDate { get; set; }

        public string LockType { get; set; }

        public int Luid { get; set; }

        public double? MagSpacingDrop { get; set; }

        public string MaintenanceComments { get; set; }

        public double? MaxDlsDrop { get; set; }

        public int? MaxwellDrop { get; set; }

        public double? MonelId { get; set; }

        public string MonitoringCompanyDrop { get; set; }

        public double? MudDensityDrop { get; set; }

        public double? MudPv { get; set; }

        public double? MudPvTempDrop { get; set; }

        public string MudTypeDrop { get; set; }

        public double? MudViscosityDrop { get; set; }

        public string OrderStatus { get; set; }

        public LoadoutEdp ParentLoadout { get; set; }

        [ForeignKey(nameof(ParentLoadout))]
        public int? ParentLoadoutId { get; set; }

        public double? PlannedFlowRateDrop { get; set; }

        public double? PlannedFlowRateMinDrop { get; set; }

        public string Qtrac1Cguid { get; set; }

        public string Qtrac1CrequestId { get; set; }

        public SiteLookup RedirectDestSite { get; set; }

        [ForeignKey(nameof(RedirectDestSite))]
        public int? RedirectDestSiteId { get; set; }

        public SiteLookup RedirectSourceSite { get; set; }

        [ForeignKey(nameof(RedirectSourceSite))]
        public int? RedirectSourceSiteId { get; set; }

        public DateTime? RmShipDate { get; set; }

        public int? Rx5 { get; set; }

        public double? SeaDepDrop { get; set; }

        public DateTime? ShipDate { get; set; }

        public string ShipDateStatus { get; set; }

        public int? ShipDateVersion { get; set; }

        public string ShippingInstructions { get; set; }

        public double? StandPressDrop { get; set; }

        public DateTime? StartDate { get; set; }

        public double? StartDepthMdDrop { get; set; }

        public string StatusDrop { get; set; }

        public string SubmittedByLdapAlias { get; set; }

        public DateTime? SubmittedByDate { get; set; }

        public int? SubmittedByGin { get; set; }

        public double? SurfTempDrop { get; set; }

        public virtual ICollection<TcoDataEdp> TcoData { get; set; }

        public bool Template { get; set; }

        public string ToolOrderName { get; set; }

        public int? ToolVersion { get; set; }

        public string TruckingCompanyDrop { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }

        public int? VersionNumber { get; set; }
    }
}