#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    public class LrdeRun
    {
        public LrdeRun()
        {
            LrdeRunAttachment = new HashSet<LrdeRunAttachment>();
            LrdeRunAttribute = new HashSet<LrdeRunAttribute>();
            LrdeRunEquipment = new HashSet<LrdeRunEquipment>();
            LrdeRunOutOfSpec = new HashSet<LrdeRunOutOfSpec>();
        }

        public DateTime? EndDateTime { get; set; }

        public virtual Job Job { get; set; }

        public int JobId { get; set; }

        public DateTime? LastModified { get; set; }

        public string LastModifiedBy { get; set; }

        public virtual ICollection<LrdeRunAttachment> LrdeRunAttachment { get; set; }

        public virtual ICollection<LrdeRunAttribute> LrdeRunAttribute { get; set; }

        public virtual ICollection<LrdeRunEquipment> LrdeRunEquipment { get; set; }

        public int LrdeRunId { get; set; }

        public virtual ICollection<LrdeRunOutOfSpec> LrdeRunOutOfSpec { get; set; }

        public int RunNumber { get; set; }

        public DateTime? StartDateTime { get; set; }
    }
}