#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Permission
    /// </summary>
    public class Permission
    {
        public Permission()
        {
            RoleObject = new HashSet<RoleObject>();
        }

        public bool? Active { get; set; }

        public bool AdminOnly { get; set; }

        public string Code { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public bool? IsPermission { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public Object Object { get; set; }

        public int ObjectId { get; set; }

        public string PermissionDesc { get; set; }

        public int PermissionId { get; set; }

        public int PermissionSiteId { get; set; }

        public ICollection<RoleObject> RoleObject { get; set; }
    }
}