#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     This class represents table PERSONNEL_ON_BOARD from QTrac database
    /// </summary>
    public class PersonnelOnBoard
    {
        public DateTime? ArrivalDate { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string CreatedUser { get; set; }

        public int? DaysOnBoard { get; set; }

        public DateTime? DepartureDate { get; set; }

        public string Function { get; set; }

        public int? Gin { get; set; }

        public PersonnelMaster GinNavigation { get; set; }

        public int Id { get; set; }

        public int? JobId { get; set; }

        public DateTime? PobDate { get; set; }

        public Rig Rig { get; set; }

        public int? RigId { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }
    }
}