#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The rcontrol Class
    ///     Represents the Database model for the rcontrol table
    /// </summary>
    public class RControl
    {
        public bool? Active { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public int? DisplayWidth { get; set; }

        public int? EtraceId { get; set; }

        public int Id { get; set; }

        public string LastmodifiedBy { get; set; }

        public int? MessageActive { get; set; }

        public string MessgaeDisplay { get; set; }

        public int? ParentId { get; set; }

        public int? RMasterAttributeId { get; set; }

        public int? RToolOptionTypeId { get; set; }

        public string ToolTip { get; set; }

        public DateTime? UpdatedDate { get; set; }
    }
}