#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Ref Segment class
    /// </summary>
    public class RefSegment
    {
        public RefSegment()
        {
            Site = new HashSet<Site>();
            RefInBaseAttribute = new HashSet<RefInBaseAttribute>();
        }

        public bool? Active { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public string ImageName { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public ICollection<RefInBaseAttribute> RefInBaseAttribute { get; set; }

        public int RefSegmentId { get; set; }

        public int RefSegmentSiteId { get; set; }

        public string SegmentName { get; set; }

        public ICollection<Site> Site { get; set; }

        public string SlbOrgName { get; set; }
    }
}