#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The Rig Class
    ///     Represents the Database model for the Rig table
    /// </summary>
    public class Rig
    {
        public bool? Active { get; set; }

        public string AltRigName { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string CreatedUser { get; set; }

        public string CrmId { get; set; }

        public string CrmRigLocation { get; set; }

        public string CrmRigName { get; set; }

        public string CrmRigType { get; set; }

        public string Description { get; set; }

        public string Email { get; set; }

        public int Id { get; set; }

        public string IpAddress { get; set; }

        public string Name { get; set; }

        public ICollection<PersonnelOnBoard> PersonnelOnBoard { get; set; }

        public string PhoneNumber { get; set; }

        public int? RigTypeId { get; set; }

        public string SiebelId { get; set; }

        public int? SourceId { get; set; }

        public string SourceSystem { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }
    }
}