#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The RMasterAttribute Class
    ///     Represents the Database model for the RMasterAttribute table
    /// </summary>
    public class RMasterAttribute
    {
        public string CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string DefaultUom { get; set; }

        public int Id { get; set; }

        public string LastmodifiedBy { get; set; }

        public DateTime? LastmodifiedDate { get; set; }

        public string Name { get; set; }

        public string OptionName { get; set; }

        public RDimension RDimension { get; set; }

        [ForeignKey(nameof(RDimension))]
        public int? RDimensionId { get; set; }

        public int? RMasterAttributeTypeId { get; set; }
    }
}