#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The RTcoOption Class
    ///     Represents the Database model for the RTcoOption table
    /// </summary>
    public class RTcoOption
    {
        public DateTime? ActivationDate { get; set; }

        public bool Active { get; set; }

        public string CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string DefaultValueFormula { get; set; }

        public string DisplayName { get; set; }

        public int? DisplayOrder { get; set; }

        public DateTime? ExpiryDate { get; set; }

        public int? Group { get; set; }

        public int HeaderType { get; set; }

        public int Id { get; set; }

        public bool? IsMandatory { get; set; }

        public bool? IsReadOnly { get; set; }

        public string LastmodifiedBy { get; set; }

        public DateTime? LastmodifiedDate { get; set; }

        public string MaxValueFormula { get; set; }

        public string MinValueFormula { get; set; }

        public virtual RControl RControl { get; set; }

        [ForeignKey(nameof(RControl))]
        public int? RControlId { get; set; }

        public virtual RMasterAttribute RMasterAttribute { get; set; }

        [ForeignKey(nameof(RMasterAttribute))]
        public int? RMasterAttributeId { get; set; }

        public virtual RTcoConfiguration RTcoConfiguration { get; set; }

        [ForeignKey(nameof(RTcoConfiguration))]
        public int? RTcoConfigurationId { get; set; }
    }
}