#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The RToolOptions Class
    ///     Represents the Database model for the RToolOptions table
    /// </summary>
    public class RToolOptions
    {
        public string AbbreviatedName { get; set; }

        public bool? Active { get; set; }

        public int? ColumnDrop { get; set; }

        public DateTime? Created { get; set; }

        public string CreatedBy { get; set; }

        public string DefaultValueFormula { get; set; }

        public bool? DisplayOnImage { get; set; }

        public bool? DisplayOptionName { get; set; }

        public bool? DisplayOptionValue { get; set; }

        public int? DisplayOrder { get; set; }

        public int? EtraceId { get; set; }

        public int? Group { get; set; }

        public int Id { get; set; }

        public bool? IsMocRequired { get; set; }

        public bool? IsReadOnly { get; set; }

        public string LastModifiedBy { get; set; }

        public bool? Mandatory { get; set; }

        public string MaxValueFormula { get; set; }

        public string MinValueFormula { get; set; }

        public int? OptionDisplayWidth { get; set; }

        public string OptionListCodeDrop { get; set; }

        public string OptionName { get; set; }

        public string OptionTypeDrop { get; set; }

        public int? PositionOnImage { get; set; }

        public bool? PositionOnLeft { get; set; }

        public int? RControlId { get; set; }

        public int? RDimensionId { get; set; }

        public string Remarks { get; set; }

        public int? RowDrop { get; set; }

        public bool? ShowInShortDesc { get; set; }

        public int ToolMasterId { get; set; }

        public int? TypeOfValidation { get; set; }

        public DateTime? Updated { get; set; }
    }
}