#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The Sdmcell Class
    ///     Represents the Database model for the SDMCell table
    /// </summary>
    public class Sdmcell
    {
        public string CreatedBy { get; set; }

        public DateTime? Createddate { get; set; }

        public int? DistrictId { get; set; }

        public int Id { get; set; }

        [ForeignKey(nameof(Job))]
        public int? IDistrictId { get; set; }

        public Job Job { get; set; }

        public string Modifiedby { get; set; }

        public DateTime? Modifieddate { get; set; }

        public string SdmcellName { get; set; }
    }
}