#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Site class
    /// </summary>
    public class Site
    {
        public string Address1 { get; set; }

        public string Address2 { get; set; }

        public bool? AsMaintainedFlag { get; set; }

        public string ContactPerson { get; set; }

        public string Country { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public int DaysAccounted { get; set; }

        public bool? DfpmanualSwpsFlag { get; set; }

        public string DfpstoresLocationCode { get; set; }

        public int? FacilityId { get; set; }

        public string FaxNumber { get; set; }

        public string FmsDistrictNbr { get; set; }

        public bool? FmsJob { get; set; }

        public bool? FmsMovement { get; set; }

        public bool? FmsWo { get; set; }

        public string GtCountryCode { get; set; }

        public string Hierarchy { get; set; }

        public bool InBasePosition { get; set; }

        public int? InspectionStd { get; set; }

        public bool? IsCompetency { get; set; }

        public double? LaborCost { get; set; }

        public bool LaborCostMandatory { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public string LeafType { get; set; }

        public int? LocationHierarchyId { get; set; }

        public int? MachineShopStd { get; set; }

        public bool? ManualTpmwoflag { get; set; }

        public bool? MovementTimeLimit { get; set; }

        public bool? PaperlessFlag { get; set; }

        public bool PartsReqdMandatory { get; set; }

        public string PhoneNumber { get; set; }

        public bool? Qtrac1Cflag { get; set; }

        public int? RefGmtId { get; set; }

        public int? RefSegmentId { get; set; }

        public string RentalSite { get; set; }

        public string SiteCode { get; set; }

        public int SiteId { get; set; }

        public string SiteName { get; set; }

        public bool? SiteType { get; set; }

        public bool SplitDmjobs { get; set; }

        public bool SplitDtrjobs { get; set; }

        public string Status { get; set; }

        public string StoresCompanyCode { get; set; }

        public string StoresLocationCode { get; set; }

        public string StraightHours { get; set; }

        public bool? TlmSite { get; set; }

        public int? BusinessLine { get; set; }

        public int? SubBusinessLine { get; set; }

        public bool TlmWoewebFlag { get; set; }

        public bool SapFlag { get; set; }

        public bool? MupFlag { get; set; }

    }
}