#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     The TcoData Class
    ///     Represents the Database model for the TcoData table
    /// </summary>
    public class TcoDataEdp
    {
        public string CreatedBy { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string CustValue { get; set; }

        public int Id { get; set; }

        public string LastmodifiedBy { get; set; }

        public DateTime? LastmodifiedDate { get; set; }

        public virtual LoadoutEdp Loadout { get; set; }

        [ForeignKey(nameof(Loadout))]
        public int LoadoutId { get; set; }

        public RMasterAttribute RMasterAttribute { get; set; }

        [ForeignKey(nameof(RMasterAttribute))]
        public int? RMasterAttributeId { get; set; }

        public int? RMasterValueId { get; set; }

        public RTcoOption RTcoOption { get; set; }

        [ForeignKey(nameof(RTcoOption))]
        public int? RTcoOptionId { get; set; }
    }
}