#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     Table which is used to get the status for Product Groups and Product Lines of TCO
    /// </summary>
    public class TcoPGPL
    {
        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public int ID { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public int LoadoutId { get; set; }

        public int ProductGroupId { get; set; }

        public string ProductGroupStatus { get; set; }

        public int ProductLineId { get; set; }

        public string ProductLineStatus { get; set; }

        public int TcoToolsetId { get; set; }
    }
}