#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     TCOToolSet Entity Class.
    /// </summary>
    public class TCOToolSet
    {
        public virtual Site AcceptedSite { get; set; }

        public int? AcceptedSiteid { get; set; }

        public DateTime? ActualShipDate { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public Equipment Equipment { get; set; }

        [ForeignKey(nameof(Equipment))]
        public int? EquipmentId { get; set; }

        [ForeignKey(nameof(Loadout))]
        public int? EtraceLoadOutId { get; set; }

        [ForeignKey(nameof(LoadoutTool))]
        public int EtraceLoadToolId { get; set; }

        public int? EtraceTcoId { get; set; }

        public string Fcdescription { get; set; }

        public bool? IsToolset { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public virtual Loadout Loadout { get; set; }

        public virtual LoadoutTool LoadoutTool { get; set; }

        public int? MovementHdrId { get; set; }

        public virtual TCOToolSet ParentTcotoolset { get; set; }

        public int? ParentTcotoolsetId { get; set; }

        public DateTime? PlannedShipDate { get; set; }

        public string Qtrac1Cguid { get; set; }

        public string Qtrac1CrequestId { get; set; }

        public int? QuantityNo { get; set; }

        public string RealizationNumber { get; set; }

        public virtual Site RedirectedToSite { get; set; }

        [ForeignKey(nameof(RedirectedToSite))]
        public int? RedirectedToSiteId { get; set; }

        [ForeignKey("RefRedirectionType")]
        public int? RedirectedTypeId { get; set; }

        public bool? RedirectRejectFlag { get; set; }

        public RefRedirectionType RefRedirectionType { get; set; }

        public RToolOrderStatus RToolOrderStatus { get; set; }

        public string ShipmentNumber { get; set; }

        [ForeignKey("RToolOrderStatus")]
        public int? StatusId { get; set; }

        public string SubstituteReason { get; set; }

        public int? SubstituteToolId { get; set; }

        public string SubstituteWhy { get; set; }

        public string SubstituteWhyComment { get; set; }

        public int TcotoolsetId { get; set; }

        public Site TcotoolsetSite { get; set; }

        [ForeignKey(nameof(TcotoolsetSite))]
        public int? TcotoolsetSiteId { get; set; }

        public string TcotoolsetStatus { get; set; }

        public int? ToolReqId { get; set; }

        public int? ToolsetHistoryHdrId { get; set; }

        public int? ToolsetId { get; set; }

        public int? TroLoadoutId { get; set; }
    }
}