#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     User
    /// </summary>
    public class User
    {
        public User()
        {
            UserRoles = new HashSet<UserRoles>();
        }

        public bool? Active { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public string Email { get; set; }

        public string FirstName { get; set; }

        public string GinNo { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public string LastName { get; set; }

        public string Ldapalias { get; set; }

        public RefResidentStatus RefResidentStatus { get; set; }

        public int? RefResidentStatusId { get; set; }

        public string Uid { get; set; }

        public int UserId { get; set; }

        public ICollection<UserRoles> UserRoles { get; set; }

        public int UserSiteId { get; set; }
    }
}