#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     This class represents table UserTablecolumnsCustomizations from QTrac database
    /// </summary>
    public class UserTablecolumnsCustomizations
    {
        public string ColumnDisplayString { get; set; }

        public int? ColumnId { get; set; }

        public int? DisplayOrder { get; set; }

        public int? Gin { get; set; }

        public PersonnelMaster GinNavigation { get; set; }

        public int Id { get; set; }

        public string ParentTable { get; set; }

        public int? SortColumn { get; set; }

        public string SortOrder { get; set; }

        public DateTime? UpdateDate { get; set; }

        public string UpdateUser { get; set; }
    }
}