#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     WorkOrderSwpspo class
    /// </summary>
    public class WorkOrderSwpspo
    {
        public int AvailableQuantity { get; set; }

        public string BuyerPartNum { get; set; }

        public int ConsumedQuantity { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public string Description { get; set; }

        public int Id { get; set; }

        public bool? IsUpdFromSwpssuccess { get; set; }

        public string Lineitemstatus { get; set; }

        public int LineNumber { get; set; }

        public string LineUom { get; set; }

        public int LnAccUnitCode { get; set; }

        public string LnActivityCode { get; set; }

        public string ManufacturerName { get; set; }

        public double Pocost { get; set; }

        public string Poname { get; set; }

        public string Ponumber { get; set; }

        public int Poquantity { get; set; }

        public int? RepairCost { get; set; }

        public string RepairType { get; set; }

        public string RequestedBy { get; set; }

        public string RequesterName { get; set; }

        public string SupplierId { get; set; }

        public string SupplierName { get; set; }

        public string SupplierPartNum { get; set; }

        public double TotalServicesCost { get; set; }

        public string UltimateSupplierId { get; set; }

        public double UnitPrice { get; set; }

        public string UpdatedBy { get; set; }

        public DateTime UpdatedDate { get; set; }

        public int WorkOrderId { get; set; }

        public int WoservicesId { get; set; }
    }
}