#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;

namespace Tlm.Fed.Adapters.Qtrac.Common.Models
{
    /// <summary>
    ///     WorkorderParts Tracking class
    /// </summary>
    public class WorkOrderPartsTracking
    {
        public string CaddyId { get; set; }

        public string CreatedBy { get; set; }

        public DateTime CreatedDate { get; set; }

        public bool ExistingEqp { get; set; }

        public string ExternalKey { get; set; }

        public int? FrId { get; set; }

        public int? Gtid { get; set; }

        public int Id { get; set; }

        public bool Kit { get; set; }

        public string LastModifiedBy { get; set; }

        public DateTime LastModifiedDate { get; set; }

        public string LastModifiedSite { get; set; }

        public DateTime? LastStoreStatusUpdateDate { get; set; }

        public string LotNo { get; set; }

        public string Notes { get; set; }

        public string ParentPartNo { get; set; }

        public int? ReservationLineItem { get; set; }

        public bool Returned { get; set; }

        public string SerialNo { get; set; }

        public bool Used { get; set; }

        public int WorkOrderPartsId { get; set; }
    }
}