#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using JetBrains.Annotations;

namespace Tlm.Fed.Adapters.Rite.Common.Services.ServiceModels.Organization
{
    public class OrganizationRequest
    {
        public string Area { get; set; }

        public int? AU { get; set; }

        public string AUDescription { get; set; }

        public string Country { get; set; }

        public string Description { get; set; }

        public string GeoMarket { get; set; }

        public string Location { get; set; }

        public string Segment { get; set; }

        [CanBeNull]
        public string FacilitiesID { get; set; }
    }
}