#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

namespace Tlm.Fed.Adapters.Rite.Common.Services.ServiceModels.Organization
{
    public class OrganizationDetail
    {
        public string Area { get; set; }

        public int? AU { get; set; }

        public string AUDescription { get; set; }

        public string AUOrgProfile { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public int? CustomsSecured { get; set; }

        public int? Deleted { get; set; }

        public string Description { get; set; }

        public int? FDP_District_Mapping_id { get; set; }

        public string FDP_District_Mapping_Name { get; set; }

        public string GeoMarket { get; set; }

        public int? iDistrict_Mapping_id { get; set; }

        public string iDistrict_Mapping_Name { get; set; }

        // public DateTime LastModified { get; set; }
        public string LastModified { get; set; }

        public string LastModifiedBy { get; set; }

        public string LocalDescription { get; set; }

        public string Location { get; set; }

        public int? Official { get; set; }

        public string OrgStatus { get; set; }

        public string Segment { get; set; }

        public string SubGeoMarket { get; set; }

        public string SubSegment { get; set; }

        public string SubSubSegment { get; set; }

        public string FacilitiesID { get; set; }

        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Status { get; set; }
        public string FacilityName { get; set; }

        public string Ownership { get; set; }

        public string CountryCode { get; set; }

    }
}