#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Tlm.Fed.Models.CrossDomain.Models.MasterData
{
    //
    // Summary:
    //     Specifies the classification level in the Epic hierarchy. ATTENTION: the enum
    //     numeric values should not change. See https://dev.azure.com/slb-it/es-TLM-federation/_workitems/edit/700741),
    //     even if the classification type actually moves to another level.
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EquipmentClassificationType
    {
        /// <summary>
        ///     Specifies the Group classification, which is at level 1 of the EPIC hierarchy.
        /// </summary>
        Group = 1,

        /// <summary>
        ///     Specifies the Segment classification, which is at level 2 of the EPIC hierarchy.
        /// </summary>
        ProductLine = 2,

        /// <summary>
        ///     Specifies the SubProductLine classification, which is at level 3 of the EPIC hierarchy.
        /// </summary>
        SubProductLine = 3,

        /// <summary>
        ///     Specifies the Product Family classification, which is at level 4 of the EPIC hierarchy.
        /// </summary>
        ProductFamily = 4,

        /// <summary>
        ///     Specifies the Product Line classification, which is at level 5 of the EPIC hierarchy.
        /// </summary>
        Technology = 5,

        /// <summary>
        ///     Specifies the Brand classification, which is at level 6 of the EPIC hierarchy.
        /// </summary>
        Brand = 6,

        /// <summary>
        ///     Specifies the Equipment System classification, which is at level 7 of the EPIC hierarchy.
        /// </summary>
        EquipmentSystem = 7,

        /// <summary>
        ///     Specifies the Equipment Toolset classification, which is at level 7 of the EPIC hierarchy.
        /// </summary>
        EquipmentToolset = 8,
    }
}