#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using JetBrains.Annotations;
using Tlm.Fed.Contexts.Site.Core.RepresentationModel;
using Tlm.Fed.Framework.Common.Models;
using Tlm.Fed.Framework.Internal;

namespace Tlm.Fed.Contexts.Site.Composer.EventHandlers
{
    [BulkRepresentationLoader("Site")]
    [UsedImplicitly]
    public class SiteRepresentationLoader : IBulkRepresentationLoader
    {
        private readonly IRepresentationBulkComposerAndSaver<SiteRepresentation> _siteBulkComposerAndSaver;

        public SiteRepresentationLoader(IRepresentationBulkComposerAndSaver<SiteRepresentation> siteBulkComposerAndSaver)
        {
            _siteBulkComposerAndSaver = siteBulkComposerAndSaver;
        }

        public async Task<CacheLoadInfo> Load(IEnumerable<string> keys)
        {
            try
            {
                return await _siteBulkComposerAndSaver.UpdateRepresentations(keys);
            }
            catch (Exception e)
            {
                return CacheLoadInfo.ForError(e.Message);
            }
        }
    }
}