#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using Microsoft.Data.SqlClient;
using Tlm.Sdk.Core;

namespace Tlm.Fed.Adapters.Qtrac.Common.Configuration
{
    public class QtracConnectionConfiguration
    {
        public TimeSpan? CommandTimeout { get; set; }

        public string ConnectionString { get; set; }

        public string Password { get; set; }

        public RetryOptions RetryOptions { get; set; }

        public string Username { get; set; }

        public string BuildConnectionStringFromSettings()
        {
            var connStringBuilder = new SqlConnectionStringBuilder(ConnectionString);
            if (!string.IsNullOrEmpty(Username) && !string.IsNullOrEmpty(Password))
            {
                connStringBuilder.Password = Password;
                connStringBuilder.UserID = Username;
            }

            return connStringBuilder.ConnectionString;
        }
    }
}