#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Microsoft.Extensions.Configuration;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Tlm.Fed.Adapters.Maximo.Common.Configuration;
using Tlm.Fed.Framework.Common.ServiceClient;
using Tlm.Fed.Framework.Internal;
using Tlm.Fed.Framework.Internal.Models;
using Tlm.Fed.Models.Canonical.WorkorderDomain;
using Tlm.Sdk.AspNetCore;
using Tlm.Sdk.Testing.Unit;

namespace Tlm.Fed.Adapters.Maximo.Site.Tests
{
    [TestClass]
    [UnitTestCategory]
    public class InstantiationTests : UnitTestBase
    {
        [TestMethod]
        public void Instantiate_RegistrationsGiven_NoExceptionThrown()
        {
            TryInstantiateComponent<LoadCacheCommandHandler<Tlm.Fed.Models.Canonical.SiteDomain.Site>, StartupForMaximoSiteAdapter, MaximoConfig>(
                additionalConfigurations: builder => builder.AddJsonFile("testsettings.shared.json", false));
        }
    }
}