#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Tlm.Fed.Adapters.SAP.Site.Models
{
    public class SAPSite
    {
        [JsonProperty("plant")]
        public string Plant { get; set; }

        [JsonProperty("name1")]
        public string Name1 { get; set; }

        [JsonProperty("name2")]
        public string Name2 { get; set; }

        [JsonProperty("streetNum")]
        public string StreetNumber { get; set; }

        [JsonProperty("postalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("countryKey")]
        public string CountryKey { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("busArea")]
        public string BusinessArea { get; set; }

        [JsonProperty("division")]
        public string Division { get; set; }

        [JsonProperty("locType")]
        public string LocationType { get; set; }

        [JsonProperty("plantToWrkcntr")]
        public List<SAPWorkCenter> SAPWorkCenters { get; set; }
    }
}