#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using Tlm.Fed.Models.Canonical.SiteDomain;
using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Querying;

namespace Tlm.Fed.Models.Canonical.EquipmentDemandDomain
{
    [Key("{0:D}:{1}", @"^\d+:.+$", nameof(ActiveCmmsId), nameof(SourceSystemRecordId))]
    [Updateable(UpdateMode.PatchMarkedProperties)]
    public class EquipmentDemandFulfillment : AttributedCmmsTrackedEntity
    {
        public const string AttributeNameToolsetHistoryHeaderId = "ToolsetHistoryHdrId";
        public const string AttributeNameIsToolSet = "IsToolSet";
        public const string AttributeNameEquipmentId = "EquipmentId";
        public const string AttributeNamePCV = "PCV";

        public string EquipmentId { get; set; }

        public string EquipmentSourceSystemRecordID { get; set; }

        public string EquipmentCode { get; set; }

        public string Status { get; set; }

        public string Comments { get; set; }

        public DateTime? FulfillmentDate { get; set; }

        public SiteId SiteId { get; set; }

        public SiteId FulfillmentSiteId { get; set; }

        public SiteId RedirectedToSiteId { get; set; }

        public string SerialNumber { get; set; }

        public DateTime? ShipmentDate { get; set; }

        public DateTime? PlannedShipmentDate { get; set; }

        public string ShipmentNumber { get; set; }

        public string ShipmentNumberType { get; set; }

        public string MovementType { get; set; }

        public string EquipmentStatus { get; set; }

        public string RedirectedNumber { get; set; }

        public bool IsActive => Status.IsActiveFulfillment();
    }
}