#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using Tlm.Sdk.Core.Models;

namespace Tlm.Fed.Models.Canonical.EquipmentDemandDomain
{
    [Key("{0}", @"^.+$", nameof(ActivityWkeid))]
    public class PutJobRetryRequestLogs : Entity
    {
        public string ActivityWkeid { get; set; }

        public bool ShouldRetry { get; set; }

        public DateTime FirstFailure { get; set; }

        public DateTime LastRetry { get; set; }

        public string ErrorMessage { get; set; }

        public int NumberOfRetryAttempts { get; set; }
    }
}