#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Sdk.Core.Models.Infrastructure;

namespace Tlm.Fed.Models.Canonical.UserDomain
{
    /// <summary>
    ///     Details of CmmsUserRoles.
    /// </summary>
    public class CmmsUserRole
    {
        /// <summary>
        ///     Cmms system Id.
        /// </summary>
        public CmmsId CmmsSystemId { get; set; }

        /// <summary>
        ///     Role Name.
        /// </summary>
        public string Role { get; set; }
    }
}