#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System.Threading.Tasks;
using Serilog;
using Tlm.Fed.Adapters.SAP.Site.Concrete;
using Tlm.Fed.Framework.Common;
using Tlm.Fed.Framework.Common.Models;
using Tlm.Fed.Framework.Internal;
using Tlm.Sdk.Core.Models.Infrastructure;

namespace Tlm.Fed.Adapters.SAP.Site.EventHandlers
{
    [BulkLoader(CmmsId.SAP, "Site", ContextStrategy.SiteBySite)]
    [ContextStrategy(ContextStrategy.SiteBySite)]
    public class SiteLoader : IDataLoader<SiteBasedLoadQuery>
    {
        private readonly IActionHandler<SAPSiteQuery, CacheLoadInfo> _sapSite;
        private readonly ILogger _logger;

        public SiteLoader(IActionHandler<SAPSiteQuery, CacheLoadInfo> sapSite)
        {
            _sapSite = sapSite;
            _logger = Log.Logger.ForContext(GetType());
        }

        public async Task<CacheLoadInfo> LoadAsync(SiteBasedLoadQuery query)
        {
            _logger.Information($"Loading sites for site id: {query.CommaSeparatedSiteCodes}.");
            var siteQuery = new SAPSiteQuery();
            var infoTemp = await _sapSite.Handle(siteQuery);
            _logger.Information($"Sites loaded for site id: {query.CommaSeparatedSiteCodes}");
            return infoTemp;
        }
    }
}