#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Tlm.Fed.Models.Canonical.SiteDomain;
using Tlm.Sdk.Core.Models;
using Tlm.Sdk.Core.Models.Metadata;

namespace Tlm.Fed.Models.Canonical.JobDomain
{
    [Key("{0:D}:{1}", @"^\d+:.+$", nameof(ActiveCmmsId), nameof(JobNumber))]
    [IsRoot()]
    public class Job : AttributedCmmsTrackedEntity
    {
        public const string Version = "1.0";

        public string JobNumber { get; set; }

        public string JobStatus { get; set; }

        public string Client { get; set; }

        public string RigName { get; set; }

        public string WellName { get; set; }

        public SiteId JobSiteId { get; set; }

        public string WkeId { get; set; }

        public bool? IsFDPJob { get; set; }
    }
}