#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Tlm.Fed.Contexts.Site.Core.DataStoreModel;

namespace Tlm.Fed.Contexts.Common.Services
{
    /// <summary>
    /// Interface to get master data.
    /// </summary>
    public interface IMasterDistrictDataService
    {
        /// <summary>
        /// Checks the master district data asynchronous.
        /// </summary>
        /// <param name="wkeId">The wke identifier.</param>
        /// <returns></returns>
        Task<MasterDistrict> CheckMasterDistrictDataAsync(string wkeId);
    }
}
