#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using Newtonsoft.Json;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Tlm.Fed.Adapters.Maximo.Site.Models
{
    [ExcludeFromCodeCoverage]
    public class MaximoLocation
    {
        [JsonProperty("slb_district")]
        public string SlbDistrict { get; set; }

        [JsonProperty("slb_oldsiteid")]
        public string OldProductLine { get; set; }

        [JsonProperty("slb_sub_bl")]
        public string SlbSubBusinessLine { get; set; }

        [JsonProperty("slb_sap_plant")]
        public string SlbSapPlant { get; set; }

        [JsonProperty("slb_altlaborloc")]
        public string SlbAltLaborLoc { get; set; }

        [JsonProperty("slb_ofsstoresid")]
        public string SlbOfsStoreId { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("slb_division")]
        public string SlbDivision { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("slb_basin")]
        public string SlbBasin { get; set; }

        [JsonProperty("_rowstamp")]
        public string RowStamp { get; set; }

        [JsonProperty("slb_facilitydb")]
        public string SlbFacilityDb { get; set; }

        [JsonProperty("slb_store_managedby_description")]
        public string SlbStoreManageByDescription { get; set; }

        [JsonProperty("slb_geounit")]
        public string SLBGeoUnit { get; set; }

        [JsonProperty("siteid")]
        public string SiteId { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("slb_store_managedby")]
        public string SlbStoreManageBy { get; set; }

        [JsonProperty("slb_sap_sloc")]
        public string SlbSapSloc { get; set; }

        [JsonProperty("type_description")]
        public string TypeDescription { get; set; }

        [JsonProperty("slb_country")]
        public string CountryCode { get; set; }

        [JsonProperty("slb_city")]
        public string City { get; set; }

        [JsonProperty("slb_default")]
        public string SLBDefault { get; set; }

        [JsonProperty("slb_distdesc")]
        public string SLBDistrictName { get; set; }

        [JsonProperty("slb_isstoreloc")]
        public bool IsStoreLocation { get; set; }

        [JsonProperty("slb_issaploc")]
        public bool IsSapLocation { get; set; }

        [JsonProperty("slb_usedparts_loc")]
        public bool IsUsedPartsLocation { get; set; }

        [JsonProperty("slb_optimus_loc")]
        public bool IsOptimusLocation { get; set; }

        [JsonProperty("slb_locsite")]
        public ICollection<SlbLocSite> SlbLocSiteDetails { get; set; }
    }
}