#region Header

// Schlumberger Private
// Copyright 2020 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using Tlm.Sdk.Core.Models;

namespace Tlm.Fed.Models.Canonical.WorkorderDomain
{
    public class MaterialRequest : AttributedCmmsTrackedEntity
    {
        public string Description { get; set; }

        public bool? MandatoryPartFlag { get; set; }

        public int? RequestedQuantity { get; set; }

        public DateTime? RequestedDate { get; set; }

        public string RequestStatus { get; set; }

        public string MaterialNumber { get; set; }

        public string MaterialStatus { get; set; }

        public string MaterialStatusDescription { get; set; }

        public double? UnitPrice { get; set; }

        public string PurchaseOrderNumber { get; set; }

        public int? RecommendedQuantity { get; set; }

        public string UnitOfMeasure { get; set; }

        public int? UsedQuantity { get; set; }
    }
}